name: 'Build to minikube'

on:
  push:
    branches: [ "main" ]

jobs:
  build_to_minikube:
    runs-on: laptop
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: | 
        minikube -p minikube docker-env --shell powershell | Invoke-Expression
        $tag = $env:GITHUB_SHA
        docker build . --file Dockerfile --tag "intens-praksa-be-server:$tag"

    
